# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:1-alpine

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig.json drizzle.config.ts ./
COPY src ./src

RUN bun install --frozen-lockfile

# Expose no ports (stdio communication)

CMD ["bun", "src/main.ts"]
